export const dataDiktatAsis = {
    year: 2024,
    uts_uas: "uas",
    data: [
        {
            name: "Matematika Lanjut 1",
            year: [2023],
            major: ["Teknik Elektro"],
            img: "/waves-opacity.svg",
            googleDriveLink: "https://drive.google.com/file/d/1x9HxPdQcll7uGbbKiGhrAZyTnB9Z_7ua/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Rangkaian Listrik 2",
            year: [2023],
            major: ["Teknik Elektro"],
            img: "/curve-asymmetrical.svg",
            googleDriveLink: "https://drive.google.com/file/d/1MUlGQFM6WYf2yWk3dKsACYGRtBxY-KjC/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Matematika Lanjut 2",
            year: [2023],
            major: ["Teknik Elektro"],
            img: "/wavey-fingerprint.svg",
            googleDriveLink: "https://drive.google.com/file/d/1UZMMaDCXvUrl7ENumiQczYCSGF4ag8FL/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Matematika Diskrit",
            year: [2023],
            major: ["Teknik Elektro"],
            img: "/waves-opacity.svg",
            googleDriveLink: "https://drive.google.com/file/d/1FwZw68C4hpFWiLhxihtG10117LlckKNR/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Statistika",
            year: [2023],
            major: ["Teknik Komputer"],
            img: "/curve-asymmetrical.svg",
            googleDriveLink: "https://drive.google.com/file/d/18EIqRV9hdXvr8SIuWlOp4buiHbxVsLLv/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Desain Rangkaian Elektronika/Elektronika Analog",
            year: [2023],
            major: ["Teknik Komputer", "Teknik Biomedik"],
            img: "/wavey-fingerprint.svg",
            googleDriveLink: "https://drive.google.com/file/d/1wPg3ndeR7Df-bGIE-Y5opf9962BBwpYB/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Rangkaian Listrik Tekom/Biom",
            year: [2023],
            major: ["Teknik Komputer", "Teknik Biomedik"],
            img: "/curve-asymmetrical.svg",
            googleDriveLink: "https://drive.google.com/file/d/1GDUDpTL39knbNDwNj27SPwAgpFAoXvbo/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Aljabar Linear",
            year: [2024],
            major: ["Teknik Elektro"],
            img: "/waves-opacity.svg",
            googleDriveLink: "https://drive.google.com/file/d/15s3fbocH4fKoqVSutu_GNm5AW15dbLD5/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Kalkulus",
            year: [2024],
            major: ["Teknik Elektro", "Teknik Komputer", "Teknik Biomedik"],
            img: "/wavey-fingerprint.svg",
            googleDriveLink: "https://drive.google.com/file/d/1XjM3AOwSifrDkTg8w8o4Xxn-ie0Ktjuj/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Fisika Listrik",
            year: [2024],
            major: ["Teknik Elektro", "Teknik Komputer", "Teknik Biomedik"],
            img: "/waves-opacity.svg",
            googleDriveLink: "https://drive.google.com/file/d/1FE_ItHO2dfU4gwfHZqSC76OabtkBGWaA/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Kimia Dasar",
            year: [2024],
            major: ["Teknik Biomedik"],
            img: "/wavey-fingerprint.svg",
            googleDriveLink: "https://drive.google.com/file/d/1zNnTWuHcKuJmXR4j4KlBNvMwjqek1bIe/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Matematika Lanjut 1 Biomedik",
            year: [2023],
            major: ["Teknik Biomedik"],
            img: "/curve-asymmetrical.svg",
            googleDriveLink: "https://drive.google.com/file/d/1jPi9FDD_AZ_PIOYRAfDBC2ndhPF6d6AN/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
        {
            name: "Dasar Sistem Digital",
            year: [2024],
            major: ["Teknik Komputer"],
            img: "/waves-opacity.svg",
            googleDriveLink: "https://drive.google.com/file/d/1vyNwSReVrvzoLGsbatCFF8oDX3R-8vBR/view?usp=drive_link",
            includesMeetingLink: true,
            zoomMeetingsLink: "https://www.zoom.com/?lang=null",
        },
    ]
}
export const dataProker = [
    {
        title: "Diktat dan Asistensi",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed purus mi, sollicitudin nec arcu sit amet, posuere pulvinar magna. Proin eget ex id nibh lacinia consectetur quis ac arcu.",
        cards: [
            {
                title: "Diktat dan Asistensi UTS 2025",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/diktat-asistensi",
                samePage: true,
            },
            {
                title: "Kumpulan Diktat 20xx - 20xx",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: "",
                href: "/proker-lain",
                samePage: true,
            },
            {
                title: "Jadwal Asistensi",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/proker-lain",
                samePage: true,
            },
            {
                title: "Channel Youtube Akpro",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "https://youtube.com/@akademisdankeprofesianime2024?si=O3gtqr9YrsWjGLWp",
                samePage: false,
            },
        ],
    },
    {
        title: "Placeholder one",
        description: "Pellentesque nec augue vulputate, iaculis arcu eget, semper nisl. Mauris commodo tincidunt odio, mollis porta est finibus ut. Proin vitae magna gravida, fringilla dui id, semper nulla.",
        cards: [
            {
                title: "Jadwal placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/diktat-asistensi",
                samePage: true,
            },
            {
                title: "Form - placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/proker-lain",
                samePage: true,
            },
            {
                title: "placeholder - placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/proker-lain",
                samePage: true,
            },
        ],
    },
    {
        title: "Placeholder two",
        description: "Nunc tincidunt lobortis orci at laoreet. Sed sit amet pretium dolor. Morbi sed congue magna, at aliquet risus.",
        cards: [
            {
                title: "Jadwal placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/diktat-asistensi",
                samePage: true,
            },
            {
                title: "Form - placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/proker-lain",
                samePage: true,
            },
            {
                title: "placeholder - placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/proker-lain",
                samePage: true,
            },
            {
                title: "Jadwal placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/diktat-asistensi",
                samePage: true,
            },
            {
                title: "Form - placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/proker-lain",
                samePage: true,
            },
            {
                title: "placeholder - placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/proker-lain",
                samePage: true,
            },
        ],
    },
    {
        title: "Placeholder three",
        description: "Donec dignissim, odio vitae porttitor accumsan, tortor sapien bibendum augue, vitae tincidunt nibh eros quis ipsum. Etiam quam nisl, blandit sit amet eros vitae, placerat venenatis erat. Vestibulum nisl nisl, tincidunt non suscipit at, maximus at arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet ligula justo. ",
        cards: [
            {
                title: "Form - placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/proker-lain",
                samePage: true,
            },
            {
                title: "placeholder - placeholder",
                description: "lorem ipsum",
                img: "data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
                imgAlt: " ",
                href: "/proker-lain",
                samePage: true,
            },
        ],
    },
]